rate-limit.endpoints./api/test.max-requests=5
rate-limit.endpoints./api/test.window-size-millis=60000


rate-limit.endpoints.[/api/test].max-requests=3
rate-limit.endpoints.[/api/test].window-size-millis=60000

rate-limit.endpoints.[/api/products].max-requests=5
rate-limit.endpoints.[/api/products].window-size-millis=60000

